import { chromium } from 'playwright';
import assert from 'node:assert/strict';

const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(12000);
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const button = name => page.getByRole('button', { name, exact: true });
const field = name => page.getByLabel(name, { exact: true });
const go = area => page.goto(`http://127.0.0.1:8080/redesign/${area}`);
const records = () => page.evaluate(() => JSON.parse(localStorage.getItem('cloudvalley-redesign-v1')));
const close = () => page.keyboard.press('Escape');
const confirm = async name => { await page.getByRole('alertdialog').getByRole('button', { name, exact: true }).click(); await page.getByRole('alertdialog').waitFor({ state: 'detached' }); };
try {
  await go('connections');
  await button('Ver detalle: Horizonte Capital').click();
  await button('Aprobar conexión').click(); await confirm('Aprobar conexión');
  assert.equal((await records()).find(r => r.id === 'fund4').status, 'Conectado');
  await close(); await button('Ver detalle: Río Partners').click();
  await button('Cancelar solicitud').click(); await confirm('Cancelar solicitud');
  assert.equal((await records()).find(r => r.id === 'fund3').status, 'Cancelada');
  await close(); await button('Ver detalle: North Capital').click();
  await button('Abrir documento: Modelo financiero.xlsx').click();
  await page.getByRole('dialog').getByRole('heading', { name: 'Modelo financiero.xlsx', exact: true }).waitFor();
  await close(); await button('Ver detalle: North Capital').click();
  await button('Eliminar conexión').click(); await confirm('Eliminar conexión');
  const disconnected = await records();
  assert.equal(disconnected.find(r => r.id === 'fund1').status, 'Desconectado');
  assert.equal(disconnected.find(r => r.id === 'doc2').fields.share_fund1, false);
  assert.equal(disconnected.find(r => r.id === 'report2').fields.share_fund2, true);
  await go('reports'); await button('Ver detalle: Investor update · septiembre').click();
  await field('Título de la sección').fill('Resultados verificados');
  await field('Agregar métrica').selectOption('arr');
  await button('Subir métrica 3 de sección 1').click();
  await page.getByText('Compartir con fondos conectados', { exact: true }).click();
  await field('Delta Ventures').check(); await close(); await page.reload();
  await button('Ver detalle: Investor update · septiembre').click();
  assert.equal(await field('Título de la sección').inputValue(), 'Resultados verificados');
  await page.getByText('Compartir con fondos conectados', { exact: true }).click();
  assert.equal(await field('Delta Ventures').isChecked(), true);
  await button('Guardar reporte').click();
  const report = (await records()).find(r => r.id === 'report1');
  assert.deepEqual(report.sections[0].blocks.map(b => b.metric_id), ['mrr', 'arr', 'runway']);
  assert.equal(report.fields.share_fund2, true);
  await button('Vista previa').click(); await field('Período del reporte').fill('2025-01');
  assert.equal(await page.getByText('Sin datos', { exact: true }).count(), 3);
  await go('metrics'); await button('Ver detalle: Monthly recurring revenue').click();
  assert.equal(await field('Valor').count(), 0);
  await button('Ver fuente: Stripe').click();
  await page.getByRole('dialog').getByRole('heading', { name: 'Stripe · ingresos' }).waitFor();
  await go('documents'); await button('Nueva carpeta').click();
  await field('Nombre').fill('Prueba documental'); await button('Guardar').click();
  await page.getByRole('button', { name: 'Prueba documental 0 documentos', exact: true }).click();
  await page.locator('.rd-page-header').getByRole('button', { name: 'Agregar documento' }).click();
  await field('Nombre *').fill('Archivo verificable'); await button('Continuar').click();
  await field('Archivo *').setInputFiles({ name: 'evidencia.txt', mimeType: 'text/plain', buffer: Buffer.from('contenido de prueba') });
  await button('Continuar').click(); await button('Guardar en la demo').click();
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Descargar evidencia.txt' }).click();
  const download = await downloadEvent; assert.equal(download.suggestedFilename(), 'evidencia.txt');
  const stream = await download.createReadStream(); const chunks = []; for await (const chunk of stream) chunks.push(chunk);
  assert.equal(Buffer.concat(chunks).toString(), 'contenido de prueba');
  await close(); await page.reload();
  await field('Buscar documentos y carpetas').fill('Archivo verificable');
  await button('Acciones de Archivo verificable').click(); await page.getByRole('menuitem', { name: 'Mover', exact: true }).click();
  await field('Destino').selectOption('legal'); await button('Mover').click();
  assert.equal((await records()).find(r => r.name === 'Archivo verificable').fields.folder_id, 'legal');
  await button('Acciones de Archivo verificable').click(); await page.getByRole('menuitem', { name: 'Eliminar', exact: true }).click();
  await confirm('Eliminar'); assert.equal((await records()).some(r => r.name === 'Archivo verificable'), false);
  assert.deepEqual(errors, []);
  console.log('PASS: connection lifecycle and access revocation; report blocks, sharing drafts and period preview; synced metric source; folder creation, file persistence/download, move and delete.');
} finally { await browser.close(); }
