import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
const button = name => page.getByRole('button', { name, exact: true });
const records = () => page.evaluate(() => JSON.parse(localStorage.getItem('cloudvalley-redesign-v1')));
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto('http://127.0.0.1:8080/redesign/sources');
  await button('Ver detalle: Estado de resultados').click();
  await button('Sincronizar muestra').click();
  await page.evaluate(() => {
    const rows = JSON.parse(localStorage.getItem('cloudvalley-redesign-v1'));
    rows.push({ id: 'dependent', area: 'metrics', name: 'Ingresos importados', category: 'Ingresos', value: '', status: 'Al día', detail: '', query: { type: 'aggregation', aggregation: 'sum', field_key: 'ingresos', distinct_field_key: null, filters: [] } });
    localStorage.setItem('cloudvalley-redesign-v1', JSON.stringify(rows));
    localStorage.setItem('cloudvalley-redesign-report-report2', JSON.stringify({ name: 'Borrador de prueba', sections: [], shares: {} }));
  });
  await page.reload();
  await button('Ver detalle: Estado de resultados').click();
  await button('Eliminar fuente').click();
  assert.match(await page.getByRole('alertdialog').innerText(), /Ingresos importados/);
  await page.getByRole('alertdialog').getByRole('button', { name: 'Cancelar', exact: true }).click();
  assert.equal((await records()).find(record => record.id === 'eerr').sourceRows.length, 3);
  await button('Eliminar fuente').click();
  await page.getByRole('alertdialog').getByRole('button', { name: 'Eliminar fuente', exact: true }).click();
  await page.getByRole('alertdialog').waitFor({ state: 'hidden' });
  assert.equal((await records()).some(record => record.id === 'eerr'), false);
  await page.goto('http://127.0.0.1:8080/redesign/metrics');
  assert.match(await button('Ver detalle: Ingresos importados').innerText(), /Sin datos/);
  await page.goto('http://127.0.0.1:8080/redesign/reports');
  await button('Ver detalle: Investor update · agosto').click();
  await page.getByText('Actividad de lectura', { exact: true }).click();
  await button('Simular lectura: 90 s y 75% visto').click();
  await button('Simular lectura: 90 s y 75% visto').click();
  assert.match(await page.locator('.rd-report-activity').innerText(), /2 aperturas/);
  await button('Consultar actividad al asistente').click();
  const composer = page.getByRole('textbox').last();
  await composer.fill('Explicame la actividad de lectura');
  await composer.press('Enter');
  await page.getByText(/Actividad simulada de.*2 aperturas y 180 segundos/).waitFor();
  await page.reload();
  await button('Ver detalle: Investor update \u00b7 agosto').click();
  await page.getByText('Actividad de lectura', { exact: true }).click();
  assert.match(await page.locator('.rd-report-activity').innerText(), /2 aperturas/);
  await button('Eliminar reporte').click();
  await page.getByRole('alertdialog').getByRole('button', { name: 'Eliminar reporte', exact: true }).click();
  await page.getByRole('alertdialog').waitFor({ state: 'hidden' });
  await page.reload();
  assert.equal((await records()).some(record => record.id === 'report2'), false);
  assert.equal((await records()).some(record => record.id === 'mrr'), true);
  assert.equal(await page.evaluate(() => localStorage.getItem('cloudvalley-redesign-report-report2')), null);
  assert.equal(await page.evaluate(() => localStorage.getItem('cloudvalley-redesign-activity-report2')), null);
  assert.deepEqual(errors, []);
  console.log('PASS: cancellation preserves source rows; deletion persists, warns about dependencies, clears report draft and preserves metrics.');
} finally { await browser.close(); }
