import { chromium } from 'playwright';
import assert from 'node:assert/strict';

const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(12000);
const errors = [], requests = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => { if (/api\.cloudvalley|supabase/.test(new URL(request.url()).hostname)) requests.push(request.url()); });
const button = name => page.getByRole('button', { name, exact: true });
const field = name => page.getByLabel(name, { exact: true });
const go = area => page.goto(`http://127.0.0.1:8080/redesign/${area}`);
const team = () => page.evaluate(() => JSON.parse(localStorage.getItem('cloudvalley-redesign-team')));
const confirm = async () => { await page.getByRole('alertdialog').getByRole('button', { name: 'Confirmar cambio' }).click(); await page.getByRole('alertdialog').waitFor({ state: 'detached' }); };
try {
  await go('settings'); await field('Nombre completo').fill('María Founder'); await button('Guardar perfil').click();
  await page.locator('.rd-user').getByText('María Founder', { exact: true }).waitFor();
  await button('Cambiar email').click(); await field('Nuevo email').fill('founder@example.com'); await button('Solicitar cambio en la demo').click();
  await page.getByRole('alert').getByText('Ese es tu email actual. Ingresá otro.').waitFor();
  await field('Nuevo email').fill('maria@example.com'); await button('Solicitar cambio en la demo').click();
  let email = await page.evaluate(() => JSON.parse(localStorage.getItem('cloudvalley-redesign-email')));
  assert.equal(email.current, 'founder@example.com'); assert.equal(email.pending, 'maria@example.com');
  await page.reload(); await button('Simular confirmación del email').click();
  email = await page.evaluate(() => JSON.parse(localStorage.getItem('cloudvalley-redesign-email')));
  assert.equal(email.current, 'maria@example.com'); assert.equal(email.pending, '');
  await page.locator('.rd-team-row').getByText('maria@example.com · Owner', { exact: true }).waitFor();
  await field('Foto de perfil').setInputFiles({ name: 'invalid.txt', mimeType: 'text/plain', buffer: Buffer.from('invalid') });
  await page.getByRole('alert').getByText('Elegí una imagen PNG, JPG o WEBP de hasta 5 MB.').waitFor();
  const png = await page.screenshot({ clip: { x: 0, y: 0, width: 2, height: 2 } });
  await field('Foto de perfil').setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: png });
  await page.locator('.rd-top-actions').getByRole('img', { name: 'Foto de perfil' }).waitFor();
  await page.reload(); await page.locator('.rd-top-actions').getByRole('img', { name: 'Foto de perfil' }).waitFor();
  await field('Logo de la startup').setInputFiles({ name: 'logo.png', mimeType: 'image/png', buffer: png });
  await page.locator('.rd-workspace').getByRole('img', { name: 'Logo de la startup' }).waitFor();
  await button('Quitar foto').click(); await page.locator('.rd-top-actions img').waitFor({ state: 'detached' });
  await button('Quitar owner a María Founder').click(); await confirm();
  await page.getByRole('alert').getByText('Asigná otro owner antes de quitar al último owner o salir.').waitFor();
  await button('Aprobar a Lucas Pérez').click(); assert.ok((await team()).members.some(m => m.id === 'lucas'));
  await field('Email de la persona a invitar').fill('lucas@example.com'); await button('Crear invitación de ejemplo').click();
  await page.getByRole('alert').getByText('Ese email ya pertenece al equipo o tiene una invitación o solicitud pendiente.').waitFor();
  await field('Email de la persona a invitar').fill('equipo@example.com'); await button('Crear invitación de ejemplo').click();
  assert.equal((await team()).invites.length, 1);
  await page.getByText('Probar aceptación de una invitación', { exact: true }).click();
  await button('Simular aceptación de equipo@example.com').click();
  assert.equal((await team()).invites.length, 0); assert.ok((await team()).members.some(m => m.email === 'equipo@example.com'));
  await button('Hacer owner a Ana García').click(); await confirm();
  await button('Quitar owner a María Founder').click(); await confirm();
  assert.equal(await button('Guardar startup').isDisabled(), true);
  assert.equal(await button('Crear invitación de ejemplo').count(), 0);
  await go('connections'); assert.equal(await button('Nueva solicitud').count(), 0);
  await button('Ver detalle: North Capital').click(); assert.equal(await button('Eliminar conexión').count(), 0);
  await go('settings'); await button('Salir de la startup').click(); await confirm();
  await page.getByRole('heading', { name: 'Unirte a una startup' }).waitFor();
  await go('metrics'); await page.getByRole('heading', { name: 'Unirte a una startup' }).waitFor();
  await field('Código de la startup').fill('invalido'); await button('Solicitar ingreso').click();
  await page.getByRole('alert').getByText('El código no coincide o dejó de estar vigente.').waitFor();
  await field('Código de la startup').fill((await team()).code); await button('Solicitar ingreso').click();
  await page.getByText('Controles de la demo', { exact: true }).click(); await button('Simular aprobación del ingreso').click();
  await page.locator('.rd-page-header h1').waitFor(); assert.equal((await team()).members.find(m => m.id === 'self').owner, false);
  await go('settings'); await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: 'playwright/artifacts/redesign-settings-mobile.png', fullPage: true });
  assert.deepEqual(errors, []); assert.deepEqual(requests, []);
  console.log('PASS: profile identity, local avatar/logo, email confirmation, invitations, membership decisions, ownership, leave/rejoin and permission gates; mobile overflow; no production requests.');
} finally { await browser.close(); }
