import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(12000);
const errors = [], external = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => { if (new URL(request.url()).hostname !== "fonts.googleapis.com" && /api\.cloudvalley|supabase|googleapis|stripe\.com/.test(new URL(request.url()).hostname)) external.push(request.url()); });
const button = name => page.getByRole('button', { name, exact: true });
const field = name => page.getByLabel(name, { exact: true });
const state = () => page.evaluate(() => JSON.parse(localStorage.getItem('cloudvalley-redesign-integrations')));
const go = area => page.goto(`http://127.0.0.1:8080/redesign/${area}`);
const confirm = async () => { await page.getByRole('alertdialog').getByRole('button', { name: 'Desconectar', exact: true }).click(); await page.getByRole('alertdialog').waitFor({ state: 'detached' }); };
try {
  await go('settings'); await button('Conectar Amplitude').click(); await button('Conectar en la demo').click();
  await page.getByRole('alert').getByText('Completá las credenciales de ejemplo.').waitFor();
  await field('API Key').fill('sentinel-test-key'); await field('Secret Key').fill('sentinel-test-secret'); await button('Conectar en la demo').click();
  assert.equal((await state()).providers.amplitude.status, 'connected');
  assert.equal(await page.evaluate(() => JSON.stringify(localStorage).includes('sentinel-test')), false);
  await page.getByText('Probar resultado de Amplitude', { exact: true }).click();
  await field('Resultado simulado de Amplitude').selectOption('error'); await button('Sincronizar Amplitude').click();
  assert.equal((await state()).providers.amplitude.status, 'error');
  await field('Resultado simulado de Amplitude').selectOption('success'); await button('Reintentar Amplitude').click();
  assert.equal((await state()).providers.amplitude.status, 'connected');
  await button('Desconectar Amplitude').click(); await confirm();
  assert.equal((await state()).providers.amplitude.status, 'disconnected'); await button('Conectar Amplitude').waitFor();
  await button('Conectar cuenta de Google').click(); await field('Cuenta de ejemplo').selectOption('finanzas@example.com'); await button('Simular autorización').click();
  const accountId = (await state()).accounts.find(a => a.email === 'finanzas@example.com').id;
  await button('Desconectar founder@example.com').click(); await confirm();
  await button('Gestionar hojas y mapeos').click(); await button('Agregar fuente').click(); await field('Nombre *').fill('Fuente cuenta finanzas'); await button('Continuar').click();
  assert.equal(await field('Cuenta de Google').inputValue(), accountId);
  assert.equal(await field('Cuenta de Google').locator('option').count(), 2);
  await button('Guardar borrador y gestionar cuentas').click();
  await page.getByRole('heading', { name: 'Integraciones', exact: true }).waitFor();
  assert.equal(new URL(page.url()).hash, '#integrations');
  await page.getByText('Probar estados de Google Sheets', { exact: true }).click();
  await button('Simular permiso vencido: finanzas@example.com').click();
  await button('Retomar').click(); await button('Continuar').click();
  await page.getByRole('alert').getByText('Elegí una cuenta conectada.', { exact: false }).waitFor();
  await button('Guardar borrador y gestionar cuentas').click();
  await button('Reconectar finanzas@example.com').click(); await button('Simular autorización').click();
  assert.equal((await state()).accounts.find(a => a.email === 'finanzas@example.com').id, accountId);
  await button('Retomar').click(); await button('Continuar').click(); await button('Guardar en la demo').click();
  await page.getByRole('dialog').getByText('finanzas@example.com', { exact: true }).waitFor();
  await go('settings'); await page.getByText('Probar estados de Google Sheets', { exact: true }).click();
  await field('Simular pausa del administrador').check(); assert.equal(await button('Conectar cuenta de Google').count(), 0);
  await field('Simular pausa del administrador').uncheck();
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Integration mobile overflow');
  await page.screenshot({ path: 'playwright/artifacts/redesign-integrations-mobile.png', fullPage: true });
  assert.deepEqual(errors, []); assert.deepEqual(external, []);
  console.log('PASS: provider fields, credentials never persisted, simulated sync error/retry, disconnect; Google accounts, source mapping, draft return, permission expiry/reconnect, pause; mobile and isolation.');
} finally { await browser.close(); }
