import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(12000);
const errors = [], requests = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => { if (/api\.cloudvalley|supabase/.test(new URL(request.url()).hostname)) requests.push(request.url()); });
const button = name => page.getByRole('button', { name, exact: true });
const field = name => page.getByLabel(name, { exact: true });
const go = area => page.goto(`http://127.0.0.1:8080/redesign/${area}`);
const panel = () => page.getByRole('dialog', { name: 'Asistente Founder', exact: true });
const send = async text => { await field('Mensaje al asistente').fill(text); await button('Enviar mensaje al asistente').click(); };
const close = async () => { await button('Cerrar asistente').click(); await panel().waitFor({ state: 'detached' }); };
const records = () => page.evaluate(() => JSON.parse(localStorage.getItem('cloudvalley-redesign-v1')));
try {
  for (const area of ['overview', 'metrics', 'sources', 'roadmap', 'reports', 'documents', 'connections', 'settings']) {
    await go(area); await button('Abrir asistente Founder').click(); await panel().waitFor();
    assert.ok((await panel().locator('.rd-assistant-context').innerText()).length > 15);
    await close();
  }
  await go('metrics'); await button('Nueva métrica').click(); await field('Nombre *').fill('Borrador asistido');
  await button('Revisar borrador con el asistente').click(); await send('Revisá este borrador');
  await panel().getByText('Definí la consulta', { exact: false }).waitFor(); await close();
  assert.equal(await field('Nombre *').inputValue(), 'Borrador asistido');
  await page.keyboard.press('Escape');
  await go('overview'); const before = (await records()).length;
  await button('Abrir asistente Founder').click(); await send('Proponé un reporte con mis métricas');
  assert.equal((await records()).length, before);
  await button('Crear en la demo').click(); assert.equal((await records()).length, before + 1);
  assert.equal(await button('Crear en la demo').count(), 0);
  await button('Abrir resultado').click();
  await page.getByRole('dialog').getByRole('heading', { name: /Update de Maritos/ }).waitFor();
  await field('Título de la sección').fill('Resultados editados sin guardar');
  await button('Revisar este reporte con el asistente').click(); await send('Agregá NRR');
  await button('Confirmar cambio en la demo').click();
  const report = (await records()).find(r => r.name.startsWith('Update de Maritos'));
  assert.equal(report.sections[0].title, 'Resultados editados sin guardar');
  assert.ok(report.sections[0].blocks.some(b => b.metric_id === 'nrr'));
  await close(); assert.equal(await field('Título de la sección').inputValue(), 'Resultados editados sin guardar');
  await go('settings'); await button('Abrir asistente Founder').click();
  await send('¿Dónde gestiono mis integraciones?'); await button('Abrir Integraciones').click();
  assert.equal(new URL(page.url()).hash, '#integrations');
  await button('Conectar Amplitude').click(); await button('Consultar al asistente').click(); await send('Revisá este borrador');
  await panel().getByText('Falta la clave de ejemplo.', { exact: false }).waitFor();
  await close(); await page.keyboard.press('Escape');
  await button('Abrir asistente Founder').click(); await page.getByText('Probar error de respuesta', { exact: true }).click();
  await field('Simular error').check(); await send('Mensaje que se conserva');
  assert.equal(await field('Mensaje al asistente').inputValue(), 'Mensaje que se conserva');
  await field('Simular error').uncheck(); await button('Reintentar respuesta').click();
  assert.equal(await field('Mensaje al asistente').inputValue(), '');
  await close(); await page.reload(); await button('Abrir asistente Founder').click();
  await panel().getByText('Mensaje que se conserva', { exact: true }).waitFor();
  assert.equal((await records()).filter(r => r.id === report.id).length, 1);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await panel().evaluate(element => element.scrollWidth > element.clientWidth), false);
  await page.screenshot({ path: 'playwright/artifacts/redesign-assistant-mobile.png', fullPage: false });
  await close(); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []); assert.deepEqual(requests, []);
  console.log('PASS: assistant across 8 areas, draft context, proposals require confirmation, existing report edits, exact destinations, error/retry, persistent conversation, mobile and API isolation.');
} finally { await browser.close(); }
