import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(12000);
const button = name => page.getByRole('button', { name, exact: true });
const field = name => page.getByLabel(name, { exact: true });
const records = () => page.evaluate(() => JSON.parse(localStorage.getItem('cloudvalley-redesign-v1')));
const source = async () => (await records()).find(r => r.id === 'eerr');
const errors = [], requests = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => { if (/api\.cloudvalley|supabase|sheets\.googleapis/.test(new URL(request.url()).hostname)) requests.push(request.url()); });
try {
  await page.goto('http://127.0.0.1:8080/redesign/sources');
  await button('Ver detalle: Estado de resultados').click();
  await button('Revisar muestra').click(); await page.getByRole('cell', { name: '101000', exact: true }).waitFor();
  assert.equal((await source()).sourceRows, undefined);
  await button('Sincronizar muestra').click();
  assert.equal((await source()).sourceRows.length, 3); assert.equal((await source()).sourceRuns.length, 1);
  await button('Sincronizar muestra').click();
  assert.equal((await source()).sourceRuns[0].result.inserted_rows, 0);
  assert.equal((await source()).sourceRuns[0].result.updated_rows, 0);
  const savedRows = (await source()).sourceRows;
  await page.getByText('Probar resultados de la importación', { exact: true }).click();
  await field('Resultado de la muestra').selectOption('schema'); await button('Sincronizar muestra').click();
  assert.equal((await source()).sourceRuns[0].result.status, 'error'); assert.deepEqual((await source()).sourceRows, savedRows);
  await field('Resultado de la muestra').selectOption('partial'); await button('Sincronizar muestra').click();
  assert.equal((await source()).sourceRuns[0].result.rows_rejected, 1); assert.equal((await source()).sourceRows.length, 3);
  await field('Resultado de la muestra').selectOption('success'); await button('Sincronizar muestra').click();
  assert.equal((await source()).status, 'Al día');
  await button('Revisar mapeo').click(); await button('Continuar').click(); await button('Continuar').click(); await button('Guardar en la demo').click();
  assert.equal((await source()).sourceRuns.length, 5); assert.deepEqual((await source()).sourceRows, savedRows);
  await page.reload(); await button('Ver detalle: Estado de resultados').click();
  await page.getByText('Historial de ejecuciones (5)', { exact: true }).click();
  await page.getByText('Completada · 3 filas válidas · 0 rechazadas', { exact: true }).first().waitFor();
  await page.setViewportSize({ width: 390, height: 844 }); await button('Revisar muestra').click();
  assert.equal(await page.getByRole('dialog').evaluate(element => element.scrollWidth > element.clientWidth), false);
  await page.screenshot({ path: 'playwright/artifacts/redesign-source-sync-mobile.png', fullPage: false });
  await page.goto('http://127.0.0.1:8080/redesign/settings'); await button('Desconectar founder@example.com').click();
  await page.getByRole('alertdialog').getByRole('button', { name: 'Desconectar', exact: true }).click();
  await page.goto('http://127.0.0.1:8080/redesign/sources'); await button('Ver detalle: Estado de resultados').click();
  assert.equal(await button('Sincronizar muestra').isDisabled(), true);
  await button('Revisar cuenta en Integraciones').click(); assert.equal(new URL(page.url()).hash, '#integrations');
  assert.deepEqual(errors, []); assert.deepEqual(requests, []);
  console.log('PASS: dry run, import deltas, retry, schema/partial failures preserve data, mapping edits preserve history, persistence, account gating, mobile and API isolation.');
} finally { await browser.close(); }
