import { useState, type CSSProperties } from "react";
import {
  AlertTriangle, ArrowRight, BarChart3, Bell, BookOpen, Check, ChevronRight,
  CircleHelp, Command, FileBarChart, FolderOpen, LayoutDashboard, Menu,
  MoreHorizontal, Plus, Settings, ShieldCheck, Sparkles, Upload,
  Users, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type Area = "home" | "plan" | "data" | "reports" | "library" | "connections" | "settings";
type Role = "founder" | "investor";

const sources = [
  { name: "EERR 2026", file: "grid.xlsx", age: "16 días", status: "Requiere actualización", impact: "Bloquea 3 métricas" },
  { name: "Estado de resultados", file: "Resultados 2026.xlsx", age: "15 días", status: "Requiere actualización", impact: "Afecta el reporte mensual" },
  { name: "Marketing", file: "Google Sheets", age: "13 días", status: "Sincronizada", impact: "1 métrica al día" },
];

function PrototypeNav({ active, onChange, role }: { active: Area; onChange: (area: Area) => void; role: Role }) {
  const items: { id: Area; label: string; icon: typeof LayoutDashboard; founder: boolean }[] = [
    { id: "home", label: role === "founder" ? "Hoy" : "Portfolio", icon: LayoutDashboard, founder: true },
    { id: "plan", label: "Plan", icon: Check, founder: true },
    { id: "data", label: role === "founder" ? "Datos" : "Señales", icon: BarChart3, founder: true },
    { id: "reports", label: "Reportes", icon: FileBarChart, founder: true },
    { id: "library", label: "Biblioteca", icon: FolderOpen, founder: true },
    { id: "connections", label: "Conexiones", icon: Users, founder: true },
  ];
  return <aside className="hidden md:flex w-60 shrink-0 flex-col border-r bg-card p-3">
    <div className="flex h-12 items-center gap-2 px-2 text-sm font-semibold"><span className="grid h-7 w-7 place-items-center rounded-lg bg-primary text-primary-foreground">CV</span> CloudValley <span className="ml-auto rounded bg-teal-subtle px-1.5 py-0.5 text-[10px] text-teal-dark">LAB</span></div>
    <p className="px-3 pt-7 pb-2 text-[11px] font-medium uppercase tracking-wider text-muted-foreground">Tu trabajo</p>
    <nav className="space-y-1">
      {items.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => onChange(id)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${active === id ? "bg-primary-subtle text-primary-dark" : "text-muted-foreground hover:bg-surface hover:text-foreground"}`}><Icon size={17}/>{label}</button>)}
    </nav>
    <div className="mt-auto border-t pt-3">
      <button onClick={() => onChange("settings")} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${active === "settings" ? "bg-primary-subtle text-primary-dark" : "text-muted-foreground hover:bg-surface"}`}><Settings size={17}/> Configuración</button>
      <div className="mt-3 flex items-center gap-2 px-3 py-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-teal text-xs font-semibold text-teal-foreground">MU</span><span className="min-w-0 text-left"><span className="block truncate text-xs font-medium">mario user</span><span className="block text-[11px] text-muted-foreground">Founder · Maritos V3</span></span></div>
    </div>
  </aside>;
}

function StatusPill({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral" | "warning" | "success" }) {
  const styles = tone === "warning" ? "bg-warning/20 text-warning-dark" : tone === "success" ? "bg-success/15 text-success-dark" : "bg-surface text-muted-foreground";
  return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-xs font-medium ${styles}`}>{children}</span>;
}

function Home({ go }: { go: (area: Area) => void }) {
  return <div className="space-y-7">
    <section className="rounded-2xl border bg-gradient-to-br from-primary-subtle via-card to-card p-6 sm:p-8">
      <StatusPill>Martes, 17 de septiembre</StatusPill>
      <div className="mt-4 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-semibold tracking-tight">Tu próxima mejor acción</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Actualizá EERR 2026. Desbloquea 3 métricas y deja listo tu reporte mensual.</p></div><Button size="lg" onClick={() => go("data")}><Upload/> Actualizar datos <ArrowRight/></Button></div>
    </section>
    <section><div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Lo importante ahora</h2><p className="text-sm text-muted-foreground">Una cola priorizada, no otro dashboard de cards.</p></div><Button variant="ghost" onClick={() => go("data")}>Ver todo <ArrowRight/></Button></div>
      <div className="grid gap-3 lg:grid-cols-3">
        <ActionCard icon={AlertTriangle} title="2 fuentes necesitan atención" text="Tu información financiera tiene entre 15 y 16 días." action="Resolver" onClick={() => go("data")} tone="warning"/>
        <ActionCard icon={FileBarChart} title="Reporte mensual pendiente" text="Se prepara automáticamente al actualizar los datos." action="Ver reporte" onClick={() => go("reports")}/>
        <ActionCard icon={ShieldCheck} title="Datos en buen camino" text="28 métricas están listas para compartir." action="Revisar cobertura" onClick={() => go("data")} tone="success"/>
      </div>
    </section>
    <section className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Pulso del negocio</h2><StatusPill tone="success"><Check size={13}/> Actualizado</StatusPill></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["ARR","$1.2M","+8.4%"],["MRR","$101k","+6.1%"],["Runway","18 meses","+2 meses"],["Gross margin","72%","+1.9 pp"]].map(([l,v,d]) => <div key={l} className="rounded-lg bg-surface p-3"><p className="text-xs text-muted-foreground">{l}</p><p className="mt-1 text-lg font-semibold tabular-nums">{v}</p><p className="text-xs text-success-dark">{d}</p></div>)}</div></div><div className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Próximo hito</h2><p className="mt-2 text-sm text-muted-foreground">Compartir el reporte de septiembre con tu fondo.</p><Button variant="outline" className="mt-5 w-full" onClick={() => go("reports")}>Preparar reporte <ArrowRight/></Button></div></section>
  </div>;
}

function ActionCard({ icon: Icon, title, text, action, onClick, tone }: any) { return <div className="rounded-xl border bg-card p-5"><div className={`grid h-9 w-9 place-items-center rounded-lg ${tone === "warning" ? "bg-warning/20 text-warning-dark" : tone === "success" ? "bg-success/15 text-success-dark" : "bg-primary-subtle text-primary-dark"}`}><Icon size={18}/></div><h3 className="mt-4 font-medium">{title}</h3><p className="mt-1 min-h-10 text-sm text-muted-foreground">{text}</p><button onClick={onClick} className="mt-3 inline-flex items-center gap-1 text-sm font-medium text-primary-dark">{action}<ChevronRight size={16}/></button></div> }

function DataWorkspace({ onToast }: { onToast: (t: string) => void }) {
  const [open, setOpen] = useState<string | null>(null);
  const [showAll, setShowAll] = useState(false);
  const attention = sources.filter(s => s.status !== "Sincronizada");
  return <div className="space-y-6"><section><p className="text-sm font-medium text-teal-dark">Datos</p><h1 className="mt-1 text-2xl font-semibold">Mantené tus números listos</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">No necesitás administrar fuentes, mapeos y métricas por separado. Empezá por lo que impacta tu próximo reporte.</p></section>
    <div className="rounded-xl border border-warning/40 bg-warning/10 p-4 sm:flex sm:items-center sm:justify-between"><div className="flex gap-3"><AlertTriangle className="mt-0.5 shrink-0 text-warning-dark" size={19}/><div><p className="font-medium">Dos actualizaciones bloquean tu próximo reporte</p><p className="mt-0.5 text-sm text-muted-foreground">Empezá por EERR 2026: tarda menos de un minuto.</p></div></div><Button className="mt-3 sm:mt-0" onClick={() => setOpen("EERR 2026")}>Resolver ahora <ArrowRight/></Button></div>
    <section className="rounded-xl border bg-card"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Qué necesita tu atención</h2><p className="mt-0.5 text-sm text-muted-foreground">Sólo mostramos las fuentes que tienen impacto.</p></div><StatusPill tone="warning">{attention.length} pendientes</StatusPill></div>{attention.map(s => <button key={s.name} onClick={() => setOpen(s.name)} className="grid w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-b px-5 py-4 text-left last:border-0 hover:bg-surface/60"><div className="min-w-0"><p className="font-medium">{s.name}</p><p className="mt-1 truncate text-sm text-muted-foreground">{s.impact} · Última actualización hace {s.age}</p></div><span className="inline-flex items-center gap-1 text-sm font-medium text-primary-dark">Resolver <ChevronRight size={16}/></span></button>)}</section>
    <section className="grid gap-4 lg:grid-cols-[1.25fr_1fr]"><div className="rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Tus métricas están listas</h2><p className="mt-1 text-sm text-muted-foreground">28 de 31 se pueden compartir con confianza.</p></div><StatusPill tone="success">90%</StatusPill></div><div className="mt-5 flex flex-wrap gap-2">{["ARR", "MRR", "Gross margin", "Cash"].map(metric => <span key={metric} className="rounded-lg bg-surface px-3 py-2 text-sm font-medium">{metric} <Check className="ml-1 inline text-success-dark" size={14}/></span>)}</div><button className="mt-5 text-sm font-medium text-primary-dark">Ver las métricas <ArrowRight className="inline" size={15}/></button></div><div className="rounded-xl border bg-card p-5"><h2 className="font-semibold">¿Querés ver todas las fuentes?</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Los detalles técnicos quedan disponibles cuando los necesitás, sin interrumpir este flujo.</p><Button variant="outline" className="mt-5" onClick={() => setShowAll(!showAll)}>{showAll ? "Ocultar fuentes" : "Ver fuentes"} <ChevronRight/></Button></div></section>
    {showAll && <section className="overflow-hidden rounded-xl border bg-card"><div className="border-b bg-surface/60 px-5 py-3 text-xs font-medium uppercase tracking-wide text-muted-foreground">Todas las fuentes conectadas</div>{sources.map(s => <button key={s.file} onClick={() => setOpen(s.name)} className="grid w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-b px-5 py-4 text-left last:border-0 hover:bg-surface/60"><span><span className="font-medium">{s.file}</span><span className="mt-1 block text-sm text-muted-foreground">{s.name} · {s.status}</span></span><MoreHorizontal className="text-muted-foreground" size={18}/></button>)}</section>}
    <Dialog open={!!open} onOpenChange={o => !o && setOpen(null)}><DialogContent className="max-w-xl"><DialogHeader><StatusPill tone="warning">Requiere atención</StatusPill><DialogTitle className="mt-3">Actualizá {open}</DialogTitle><DialogDescription>Esta fuente alimenta métricas visibles en tu próximo reporte. Subí una versión nueva para mantenerlas actualizadas.</DialogDescription></DialogHeader><div className="rounded-lg border bg-surface p-4"><p className="text-sm font-medium">Qué cambia al resolverlo</p><ul className="mt-2 space-y-2 text-sm text-muted-foreground"><li>• Se actualizan 3 métricas financieras.</li><li>• El reporte mensual queda listo para revisar.</li><li>• Conservamos el mapeo actual; no necesitás configurarlo de nuevo.</li></ul></div><DialogFooter><Button variant="outline" onClick={() => setOpen(null)}>Ahora no</Button><Button onClick={() => { setOpen(null); onToast("Listo para subir una nueva versión"); }}><Upload/> Subir actualización</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function Reports({ onToast }: { onToast: (t: string) => void }) { const [newReport,setNewReport]=useState(false); const [created,setCreated]=useState(false); return <div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-teal-dark">Preparar y compartir</p><h1 className="mt-1 text-2xl font-semibold">Reportes</h1><p className="mt-2 text-sm text-muted-foreground">Compartí una lectura clara del negocio, no una exportación de datos.</p></div><Button onClick={() => setNewReport(true)}><Plus/> Crear reporte</Button></section>{!created ? <div className="rounded-xl border border-dashed bg-card px-6 py-16 text-center"><div className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-primary-subtle text-primary-dark"><FileBarChart/></div><h2 className="mt-4 font-semibold">Tu primer reporte empieza con datos listos</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Vamos a incluir las métricas relevantes, señalar las que necesitan revisión y dejarte decidir qué compartir.</p><Button className="mt-5" onClick={() => setNewReport(true)}>Crear reporte mensual <ArrowRight/></Button></div> : <div className="rounded-xl border bg-card p-5"><StatusPill tone="success"><Check size={13}/> Borrador listo</StatusPill><h2 className="mt-3 text-lg font-semibold">Reporte mensual · Septiembre 2026</h2><p className="mt-1 text-sm text-muted-foreground">8 métricas incluidas · 2 requieren una nota antes de compartir.</p><div className="mt-5 flex gap-2"><Button onClick={() => onToast("Abrimos el editor de reporte")}>Revisar y compartir <ArrowRight/></Button><Button variant="outline">Vista previa</Button></div></div>}<Dialog open={newReport} onOpenChange={setNewReport}><DialogContent><DialogHeader><DialogTitle>Crear un reporte</DialogTitle><DialogDescription>Elegí un período. CloudValley propone una estructura y podés ajustarla después.</DialogDescription></DialogHeader><label className="space-y-2 text-sm font-medium">Período<Input defaultValue="Septiembre 2026" aria-label="Período del reporte"/></label><DialogFooter><Button variant="outline" onClick={() => setNewReport(false)}>Cancelar</Button><Button onClick={() => {setNewReport(false);setCreated(true);onToast("Borrador creado con 8 métricas");}}>Crear borrador <ArrowRight/></Button></DialogFooter></DialogContent></Dialog></div> }

function Plan({ onToast }: { onToast: (t: string) => void }) { const [done,setDone]=useState<string[]>(["Definir narrativa de fundraising"]); const tasks=["Actualizar datos financieros","Preparar reporte mensual","Definir narrativa de fundraising","Revisar pipeline comercial"]; return <div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-teal-dark">Ejecución</p><h1 className="mt-1 text-2xl font-semibold">Plan de fundraising</h1><p className="mt-2 text-sm text-muted-foreground">Una lista de trabajo compartida entre tu equipo y tus inversores.</p></div><Button variant="outline"><Plus/> Agregar tarea</Button></section><div className="rounded-xl border bg-card"><div className="flex items-center justify-between border-b p-5"><div><p className="font-semibold">Septiembre</p><p className="text-sm text-muted-foreground">3 de 4 prioridades completadas</p></div><StatusPill tone="success">75% listo</StatusPill></div><div>{tasks.map((task,i)=>{const checked=done.includes(task);return <button key={task} onClick={()=>setDone(checked?done.filter(x=>x!==task):[...done,task])} className="flex w-full items-center gap-3 border-b p-5 text-left last:border-0 hover:bg-surface"><span className={`grid h-5 w-5 place-items-center rounded-full border ${checked?"border-success bg-success text-success-foreground":"border-muted-foreground"}`}>{checked&&<Check size={13}/>}</span><span className={`flex-1 ${checked?"text-muted-foreground line-through":"font-medium"}`}>{task}<span className="mt-1 block text-xs no-underline text-muted-foreground">{i===0?"Impacta el reporte":"Prioridad de esta semana"}</span></span><StatusPill tone={i===0?"warning":"neutral"}>{i===0?"Ahora":"Esta semana"}</StatusPill></button>})}</div></div><div className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">Las tareas pedidas por un fondo aparecen acá con contexto, fecha y responsable. <button onClick={()=>onToast("No hay solicitudes nuevas")} className="font-medium text-primary-dark">Ver solicitudes</button></div></div> }

function Connections() { return <div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-teal-dark">Relaciones</p><h1 className="mt-1 text-2xl font-semibold">Conexiones</h1><p className="mt-2 text-sm text-muted-foreground">El contexto de cada fondo, sus pedidos y lo que compartís.</p></div><Button><Plus/> Invitar un fondo</Button></section><div className="rounded-xl border bg-card p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className="grid h-11 w-11 place-items-center rounded-lg bg-teal-subtle font-semibold text-teal-dark">NC</span><div><h2 className="font-semibold">North Capital</h2><p className="mt-1 text-sm text-muted-foreground">Conectado · acceso a 1 reporte y 1 documento</p></div></div><StatusPill tone="success">Al día</StatusPill></div><div className="mt-5 grid gap-3 border-t pt-5 sm:grid-cols-3"><Info label="Última actividad" value="Vio el reporte de agosto"/><Info label="Próximo paso" value="Compartir septiembre"/><Info label="Privacidad" value="28 métricas visibles"/></div><Button variant="outline" className="mt-5">Abrir relación <ArrowRight/></Button></div><div className="rounded-xl border border-dashed p-6 text-center"><Users className="mx-auto text-muted-foreground"/><p className="mt-3 font-medium">Sumá un fondo cuando estés listo</p><p className="mt-1 text-sm text-muted-foreground">La invitación define la relación sin exponer tus datos por defecto.</p></div></div> }
function Info({label,value}:{label:string;value:string}) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div> }

function Library() { return <div className="space-y-6"><section><p className="text-sm font-medium text-teal-dark">Compartir</p><h1 className="mt-1 text-2xl font-semibold">Biblioteca</h1><p className="mt-2 text-sm text-muted-foreground">Documentos y accesos, organizados por lo que necesitás compartir.</p></section><div className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><FolderOpen className="text-primary-dark"/><StatusPill>1 documento</StatusPill></div><h2 className="mt-5 font-semibold">Para inversores</h2><p className="mt-1 text-sm text-muted-foreground">Documentos visibles para los fondos conectados.</p><Button variant="outline" className="mt-5">Gestionar acceso <ArrowRight/></Button></div><div className="rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><BookOpen className="text-teal-dark"/><StatusPill>Privado</StatusPill></div><h2 className="mt-5 font-semibold">Trabajo interno</h2><p className="mt-1 text-sm text-muted-foreground">Material de tu equipo que todavía no compartís.</p><Button variant="outline" className="mt-5">Explorar biblioteca <ArrowRight/></Button></div></div></div> }

function SettingsPage() { return <div className="space-y-6"><section><p className="text-sm font-medium text-teal-dark">Configuración</p><h1 className="mt-1 text-2xl font-semibold">Tu espacio de trabajo</h1><p className="mt-2 text-sm text-muted-foreground">Administrá sólo lo que necesitás, sin mezclar dominios.</p></section><div className="grid gap-3 md:grid-cols-2">{[[Users,"Equipo","Miembros, roles e invitaciones"],[ShieldCheck,"Privacidad","Qué puede ver cada fondo"],[BarChart3,"Integraciones","Fuentes y automatizaciones"],[Settings,"Perfil y startup","Tu identidad y la de Maritos V3"]].map(([Icon,title,text]:any)=><button key={title} className="flex items-start gap-4 rounded-xl border bg-card p-5 text-left hover:bg-surface"><span className="grid h-10 w-10 place-items-center rounded-lg bg-surface text-primary-dark"><Icon size={19}/></span><span><span className="font-medium">{title}</span><span className="mt-1 block text-sm text-muted-foreground">{text}</span></span><ChevronRight className="ml-auto mt-2 text-muted-foreground" size={17}/></button>)}</div></div> }

export default function ProductPrototype() {
  const [area,setArea] = useState<Area>("home"); const [role,setRole] = useState<Role>("founder"); const [toast,setToast] = useState<string | null>(null); const [mobileNav,setMobileNav]=useState(false);
  const content = area === "home" ? <Home go={setArea}/> : area === "plan" ? <Plan onToast={setToast}/> : area === "data" ? <DataWorkspace onToast={setToast}/> : area === "reports" ? <Reports onToast={setToast}/> : area === "library" ? <Library/> : area === "connections" ? <Connections/> : <SettingsPage/>;
  // Paleta exclusiva del laboratorio: tinta para estructura, azul para acción,
  // esmeralda para salud. No altera los tokens ni el branding de producción.
  const palette = {
    "--background": "214 35% 98%", "--surface": "214 32% 95%", "--foreground": "222 47% 11%",
    "--card": "0 0% 100%", "--card-foreground": "222 47% 11%", "--popover": "0 0% 100%", "--popover-foreground": "222 47% 11%",
    "--primary": "217 91% 48%", "--primary-foreground": "0 0% 100%", "--primary-dark": "222 82% 35%", "--primary-light": "214 95% 76%", "--primary-lighter": "214 95% 90%", "--primary-subtle": "214 100% 96%",
    "--teal": "160 70% 35%", "--teal-foreground": "0 0% 100%", "--teal-dark": "160 72% 25%", "--teal-light": "160 60% 72%", "--teal-subtle": "160 55% 94%",
    "--muted": "214 32% 95%", "--muted-foreground": "215 16% 40%", "--tertiary": "215 14% 52%", "--border": "214 28% 89%", "--input": "214 28% 89%", "--accent": "214 32% 95%", "--accent-foreground": "222 47% 11%", "--ring": "217 91% 48%",
    "--success": "151 64% 34%", "--success-dark": "151 64% 27%", "--warning": "38 92% 48%", "--warning-dark": "31 86% 31%", "--destructive": "0 72% 51%", "--destructive-dark": "0 72% 39%",
  } as CSSProperties;
  return <div style={palette} className="min-h-screen bg-background"><div className="flex min-h-screen"><PrototypeNav active={area} onChange={setArea} role={role}/><div className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b bg-background/95 px-4 backdrop-blur sm:px-7"><div className="flex items-center gap-3"><button className="md:hidden" aria-label="Abrir navegación" onClick={()=>setMobileNav(!mobileNav)}><Menu/></button><span className="md:hidden font-semibold">CloudValley</span><div className="hidden sm:block"><p className="text-xs text-muted-foreground">Workspace</p><p className="text-sm font-medium">Maritos V3</p></div></div><div className="flex items-center gap-2"><Button variant="ghost" size="sm" className="hidden sm:inline-flex"><Command/> Buscar</Button><Button variant="ghost" size="icon" aria-label="Notificaciones"><Bell size={18}/></Button><div className="hidden rounded-lg bg-surface p-1 sm:flex"><button onClick={()=>setRole("founder")} className={`rounded-md px-2.5 py-1 text-xs ${role === "founder" ? "bg-card shadow-sm" : "text-muted-foreground"}`}>Founder</button><button onClick={()=>setRole("investor")} className={`rounded-md px-2.5 py-1 text-xs ${role === "investor" ? "bg-card shadow-sm" : "text-muted-foreground"}`}>Investor</button></div></div></header>{mobileNav && <nav className="border-b bg-card p-3 md:hidden"><div className="grid grid-cols-3 gap-1">{([ ["home","Hoy",LayoutDashboard],["plan","Plan",Check],["data","Datos",BarChart3],["reports","Reportes",FileBarChart],["library","Biblioteca",FolderOpen],["connections","Conexiones",Users] ] as const).map(([id,l,I])=><button key={id} onClick={()=>{setArea(id);setMobileNav(false)}} className={`grid place-items-center gap-1 rounded-lg py-2 text-[11px] ${area===id?"bg-primary-subtle text-primary-dark":"text-muted-foreground"}`}><I size={17}/>{l}</button>)}</div></nav>}<main className="mx-auto max-w-6xl p-5 sm:p-8 lg:p-10">{content}</main></div></div>{toast && <div role="status" className="fixed bottom-5 right-5 z-50 flex items-center gap-2 rounded-lg bg-foreground px-4 py-3 text-sm text-background shadow-lg"><Check size={16}/>{toast}<button onClick={()=>setToast(null)} aria-label="Cerrar mensaje"><X size={15}/></button></div>}</div>;
}
